import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  SALES_INITIATIVE_AGENT_NAME_FIELD_ID,
  SALES_INITIATIVE_AIRLINE_YIELD_FIELD_ID,
  SALES_INITIATIVE_ASSIGNEE_EMAIL_FIELD_ID,
  SALES_INITIATIVE_ASSIGNEE_NAME_FIELD_ID,
  SALES_INITIATIVE_BENCHMARK_YIELD_FIELD_ID,
  SALES_INITIATIVE_CATEGORY_FIELD_ID,
  SALES_INITIATIVE_COCKPIT_URL_FIELD_ID,
  SALES_INITIATIVE_CONTRIBUTION_WEEKLY_FIELD_ID,
  SALES_INITIATIVE_EXTERNAL_ID_FIELD_ID,
  SALES_INITIATIVE_LAST_SYNCED_AT_FIELD_ID,
  SALES_INITIATIVE_MARKET_YIELD_FIELD_ID,
  SALES_INITIATIVE_NAME_FIELD_ID,
  SALES_INITIATIVE_NUMBER_FIELD_ID,
  SALES_INITIATIVE_ORIGIN_DESTINATION_FIELD_ID,
  SALES_INITIATIVE_REGION_FIELD_ID,
  SALES_INITIATIVE_REVENUE_WEEKLY_FIELD_ID,
  SALES_INITIATIVE_ROUTING_FIELD_ID,
  SALES_INITIATIVE_RUN_ID_FIELD_ID,
  SALES_INITIATIVE_RUN_TIMESTAMP_FIELD_ID,
  SALES_INITIATIVE_SIMILARITY_ID_FIELD_ID,
  SALES_INITIATIVE_STATION_IATA_FIELD_ID,
  SALES_INITIATIVE_STATUS_CHANGED_AT_FIELD_ID,
  SALES_INITIATIVE_STATUS_FIELD_ID,
  SALES_INITIATIVE_TARGET_TONNES_FIELD_ID,
  SALES_INITIATIVE_TARGET_YIELD_FIELD_ID,
  SALES_INITIATIVE_TYPE_FIELD_ID,
  SALES_INITIATIVE_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

// Sales Cockpit init_type: rate = yield push, mix = O&D/product swap,
// volume = new or incremental business.
export const SALES_INITIATIVE_TYPE_OPTIONS = [
  { id: '96c92377-3eff-4c64-967a-86193087d1ea', value: 'RATE', label: 'Rate', position: 0, color: 'orange' },
  { id: '3bb511ee-29cf-48c8-87b0-2085bf57fdfe', value: 'MIX', label: 'Mix', position: 1, color: 'purple' },
  { id: '09e989e3-86a3-471f-97a5-2f37cb8333c0', value: 'VOLUME', label: 'Volume', position: 2, color: 'green' },
] as const;

// Sales Cockpit lifecycle; ARCHIVED_* variants collapse onto ARCHIVED.
export const SALES_INITIATIVE_STATUS_OPTIONS = [
  { id: '399323ec-ee70-48d6-b69e-60d7cab56c45', value: 'PENDING', label: 'Pending', position: 0, color: 'gray' },
  { id: '3cd7fd28-2310-47af-a065-47ba218cc64b', value: 'ACCEPTED', label: 'Accepted', position: 1, color: 'blue' },
  { id: '3b38c410-b6ed-472d-b33d-44c6fb564bf5', value: 'COMPLETED', label: 'Completed', position: 2, color: 'green' },
  { id: 'aa568388-0402-4acf-9f50-ad711418ba71', value: 'SNOOZED', label: 'Snoozed', position: 3, color: 'yellow' },
  { id: '6edb1fdd-6039-4f3b-8e9b-68ebac3339e7', value: 'DISMISSED', label: 'Dismissed', position: 4, color: 'red' },
  { id: 'a78530d5-3072-4d80-997f-b8c659c2be14', value: 'CLOSED', label: 'Closed', position: 5, color: 'gray' },
  { id: 'b2999a44-da6b-493d-b053-da110a6abb51', value: 'ARCHIVED', label: 'Archived', position: 6, color: 'gray' },
] as const;

export default defineObject({
  universalIdentifier: SALES_INITIATIVE_UNIVERSAL_IDENTIFIER,
  nameSingular: 'salesInitiative',
  namePlural: 'salesInitiatives',
  labelSingular: 'Sales initiative',
  labelPlural: 'Sales initiatives',
  description:
    'A Sales Cockpit initiative: a costed, agent-and-lane-specific sales action, synced from the cockpit',
  icon: 'IconTargetArrow',
  labelIdentifierFieldMetadataUniversalIdentifier: SALES_INITIATIVE_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: SALES_INITIATIVE_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Title',
      icon: 'IconTargetArrow',
    },
    {
      universalIdentifier: SALES_INITIATIVE_EXTERNAL_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'externalId',
      label: 'Cockpit id',
      description: 'Sales Cockpit initiative id; the sync key',
      icon: 'IconHash',
    },
    {
      universalIdentifier: SALES_INITIATIVE_RUN_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'runId',
      label: 'Run id',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_SIMILARITY_ID_FIELD_ID,
      type: FieldType.TEXT,
      name: 'similarityId',
      label: 'Similarity id',
      description: 'Stable cross-run identity (init number + station + O&D + agent + routing)',
      icon: 'IconHash',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_NUMBER_FIELD_ID,
      type: FieldType.TEXT,
      name: 'initiativeNumber',
      label: 'Initiative number',
      description: 'Sales Cockpit rule number, e.g. 3.1 = develop new business',
      icon: 'IconListNumbers',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_CATEGORY_FIELD_ID,
      type: FieldType.TEXT,
      name: 'category',
      label: 'Category',
      description: 'Sales Cockpit rule code, e.g. GREEN-VP-NECS',
      icon: 'IconTag',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'initiativeType',
      label: 'Type',
      icon: 'IconCategory',
      isNullable: true,
      options: [...SALES_INITIATIVE_TYPE_OPTIONS],
    },
    {
      universalIdentifier: SALES_INITIATIVE_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: "'PENDING'",
      options: [...SALES_INITIATIVE_STATUS_OPTIONS],
    },
    {
      universalIdentifier: SALES_INITIATIVE_AGENT_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'agentName',
      label: 'Agent name',
      description: 'Forwarder name as the Sales Cockpit knows it (WACD agent name)',
      icon: 'IconBuildingSkyscraper',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_STATION_IATA_FIELD_ID,
      type: FieldType.TEXT,
      name: 'stationIata',
      label: 'Station',
      icon: 'IconPlane',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_ORIGIN_DESTINATION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'originDestination',
      label: 'O&D',
      icon: 'IconRoute',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_ROUTING_FIELD_ID,
      type: FieldType.TEXT,
      name: 'routing',
      label: 'Routing',
      description: 'Full routing incl. transfer points, e.g. HKG-DXB-AMS',
      icon: 'IconRoute',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_REGION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'region',
      label: 'Region',
      icon: 'IconMapPin',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_TARGET_TONNES_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'targetWeightTonnes',
      label: 'Target tonnes / week',
      icon: 'IconScale',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_TARGET_YIELD_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'targetYield',
      label: 'Target yield (USD/kg)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_AIRLINE_YIELD_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'airlineYield',
      label: 'Airline yield (USD/kg)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_MARKET_YIELD_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'marketYield',
      label: 'Market yield (USD/kg)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_BENCHMARK_YIELD_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'benchmarkYield',
      label: 'Benchmark yield (USD/kg)',
      icon: 'IconCurrencyDollar',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_REVENUE_WEEKLY_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'revenueWeekly',
      label: 'Revenue upside / week',
      icon: 'IconCoin',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_CONTRIBUTION_WEEKLY_FIELD_ID,
      type: FieldType.CURRENCY,
      name: 'contributionWeekly',
      label: 'Contribution / week',
      icon: 'IconCoin',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_ASSIGNEE_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'assigneeName',
      label: 'Cockpit assignee',
      icon: 'IconUser',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_ASSIGNEE_EMAIL_FIELD_ID,
      type: FieldType.TEXT,
      name: 'assigneeEmail',
      label: 'Cockpit assignee email',
      icon: 'IconMail',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_RUN_TIMESTAMP_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'runTimestamp',
      label: 'Generated at',
      description: 'When the Sales Cockpit run that produced this card finished',
      icon: 'IconCalendar',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_STATUS_CHANGED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'statusChangedAt',
      label: 'Status changed at',
      icon: 'IconClock',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_LAST_SYNCED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'lastSyncedAt',
      label: 'Last synced at',
      icon: 'IconRefresh',
      isNullable: true,
    },
    {
      universalIdentifier: SALES_INITIATIVE_COCKPIT_URL_FIELD_ID,
      type: FieldType.LINKS,
      name: 'cockpitUrl',
      label: 'Open in Sales Cockpit',
      icon: 'IconExternalLink',
      isNullable: true,
    },
  ],
});
